/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppMoodRouteImport } from './routes/_app.mood'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppWellnessIndexRouteImport } from './routes/_app.wellness.index'
import { Route as AppWellnessSymptomsRouteImport } from './routes/_app.wellness.symptoms'
import { Route as AppWellnessGuideRouteImport } from './routes/_app.wellness.guide'
import { Route as AppWellnessCycleRouteImport } from './routes/_app.wellness.cycle'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodRoute = AppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessIndexRoute = AppWellnessIndexRouteImport.update({
  id: '/wellness/',
  path: '/wellness/',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessSymptomsRoute = AppWellnessSymptomsRouteImport.update({
  id: '/wellness/symptoms',
  path: '/wellness/symptoms',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessGuideRoute = AppWellnessGuideRouteImport.update({
  id: '/wellness/guide',
  path: '/wellness/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessCycleRoute = AppWellnessCycleRouteImport.update({
  id: '/wellness/cycle',
  path: '/wellness/cycle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal': typeof AppJournalRoute
  '/mood': typeof AppMoodRoute
  '/nutrition': typeof AppNutritionRoute
  '/wellness/cycle': typeof AppWellnessCycleRoute
  '/wellness/guide': typeof AppWellnessGuideRoute
  '/wellness/symptoms': typeof AppWellnessSymptomsRoute
  '/wellness/': typeof AppWellnessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal': typeof AppJournalRoute
  '/mood': typeof AppMoodRoute
  '/nutrition': typeof AppNutritionRoute
  '/wellness/cycle': typeof AppWellnessCycleRoute
  '/wellness/guide': typeof AppWellnessGuideRoute
  '/wellness/symptoms': typeof AppWellnessSymptomsRoute
  '/wellness': typeof AppWellnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/mood': typeof AppMoodRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/wellness/cycle': typeof AppWellnessCycleRoute
  '/_app/wellness/guide': typeof AppWellnessGuideRoute
  '/_app/wellness/symptoms': typeof AppWellnessSymptomsRoute
  '/_app/wellness/': typeof AppWellnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/nutrition'
    | '/wellness/cycle'
    | '/wellness/guide'
    | '/wellness/symptoms'
    | '/wellness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/journal'
    | '/mood'
    | '/nutrition'
    | '/wellness/cycle'
    | '/wellness/guide'
    | '/wellness/symptoms'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/journal'
    | '/_app/mood'
    | '/_app/nutrition'
    | '/_app/wellness/cycle'
    | '/_app/wellness/guide'
    | '/_app/wellness/symptoms'
    | '/_app/wellness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mood': {
      id: '/_app/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof AppMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/': {
      id: '/_app/wellness/'
      path: '/wellness'
      fullPath: '/wellness/'
      preLoaderRoute: typeof AppWellnessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/symptoms': {
      id: '/_app/wellness/symptoms'
      path: '/wellness/symptoms'
      fullPath: '/wellness/symptoms'
      preLoaderRoute: typeof AppWellnessSymptomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/guide': {
      id: '/_app/wellness/guide'
      path: '/wellness/guide'
      fullPath: '/wellness/guide'
      preLoaderRoute: typeof AppWellnessGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/cycle': {
      id: '/_app/wellness/cycle'
      path: '/wellness/cycle'
      fullPath: '/wellness/cycle'
      preLoaderRoute: typeof AppWellnessCycleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMoodRoute: typeof AppMoodRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppWellnessCycleRoute: typeof AppWellnessCycleRoute
  AppWellnessGuideRoute: typeof AppWellnessGuideRoute
  AppWellnessSymptomsRoute: typeof AppWellnessSymptomsRoute
  AppWellnessIndexRoute: typeof AppWellnessIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppJournalRoute: AppJournalRoute,
  AppMoodRoute: AppMoodRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppWellnessCycleRoute: AppWellnessCycleRoute,
  AppWellnessGuideRoute: AppWellnessGuideRoute,
  AppWellnessSymptomsRoute: AppWellnessSymptomsRoute,
  AppWellnessIndexRoute: AppWellnessIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
